### ISSUE TITLE
react-native link does not link Android assets

### ISSUE THREAD

**Issue by annelorraineuy** [Tavernari/react-native-volume-controller#2]
Hi! Thanks for this. I'd love to use your package but ran into some issues.

Running `react-native link react-native-volume-controller` only links iOS assets, not android.

```
react-native version: 0.39.2
OS: MacOS
```

Also, I can't find `Module Settings` in Android Studio. Would you please add a step-by-step instruction on what code we should add into MainApplication.java instead? Thank you very much.

**Comment by Tavernari** [comment]
Hi,

Thanks for using my lib and you are welcome to update anything.
I did a push with corrections, maybe work. If you find some issue pls report here.

👨‍💻
