### ISSUE TITLE
update Event name in Android

### ISSUE THREAD

**Issue by hendraneo** [Tavernari/react-native-volume-controller#5]
Eventname should be VolumeControllerValueUpdatedEvent. But in your android project is streamingOpen.

Line 79 should be:
sendEvent(this.context, "VolumeControllerValueUpdatedEvent", params);

Volume send should be devided by max_volumes

Line 76 should be:
float volume = audioManager.getStreamVolume(AudioManager.STREAM_MUSIC)/max_volume;

**Comment by Tavernari** [comment]
Thanks, I will change it.

Sorry my delay, my life was very busy..
